apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dawncraft
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-builder
      path: apps/projects/incubator/gameservers/dawncraft/deployment
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: minecraft