kind: Cluster
name: homelab-dev
talos:
  version: v1.7.4
kubernetes:
  version: 1.30.0
features:
  enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
  - name: storage
    file: patches/storage.yaml

---
kind: ControlPlane
machineClass:
  name: homelab-control-plane
  size: 2
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machineClass:
  name: homelab-worker
  size: unlimited
patches:
  - name: disks
    file: patches/disks.yaml
