kind: Cluster
name: home-dhe
talos:
  version: v1.7.6
kubernetes:
  version: 1.30.1
# features:
#   enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
  - name: storage
    file: patches/storage.yaml
---
kind: ControlPlane
machineClass:
  name: dhe-control-planes
  size: 3
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machineClass:
  name: dhe-workers
  size: 2
patches:
  - name: disks
    file: patches/disks.yaml
