kind: Cluster
name: home-dhe
talos:
  version: v1.8.4
kubernetes:
  version: 1.30.9
# features:
#   enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
  # Required by Longhorn
  # - name: storage
  #   file: patches/storage.yaml
---
kind: ControlPlane
machineClass:
  name: dhe-control-planes
  size: 3
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: cluster-secret
    file: patches/home-dhe-cluster.yaml
  - name: monitoring
    file: patches/monitoring.yaml
---
kind: Workers
name: workers
machineClass:
  name: dhe-workers
  size: 3
# Required by Longhorn
# patches:
#   - name: disks
#     file: patches/disks.yaml
