kind: Cluster
name: storage-dhe
talos:
  version: v1.7.4
kubernetes:
  version: 1.30.2
# features:
#   enableWorkloadProxy: true
patches:
  - name: cni
    file: patches/cni.yaml
  - name: storage
    file: patches/storage.yaml
  - name: untainted
    file: patches/untainted.yaml
---
kind: ControlPlane
machineClass:
  name: dhe-storage-control-planes
  size: 2
patches:
  - name: cilium
    file: patches/cilium.yaml
  - name: argocd
    file: patches/argocd.yaml
  - name: monitoring
    file: patches/monitoring.yaml
  - name: disks
    file: patches/disks.yaml
