apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: conan-exiles-server
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: conan-exiles
  source:
    repoURL: https://kubelize.github.io/game-servers/
    targetRevision: 0.1.0
    chart: conan-exiles-server
    helm:
      parameters: []
      values: |
        # Default values for palserver.
        # This is a YAML-formatted file.
        # Declare variables to be passed into your templates.

        replicaCount: 1

        image:
          repository: kubelize/conan-exiles-server
          pullPolicy: Always
          # Overrides the image tag whose default is the chart appVersion.
          tag: "0.0.1"

        imagePullSecrets: []
        nameOverride: ""
        fullnameOverride: ""

        runserver:
          namespace: conan-exiles
          config: |
            #!/bin/bash
            /home/steam/steamcmd/steamcmd.sh +@sSteamCmdForcePlatformType windows +login anonymous +app_update 443030 +quit
            export WINEARCH=win64
            export WINEPREFIX=/home/steam/.wine64
            xvfb-run --auto-servernum --server-args='-screen 0 640x480x24:32' wine /home/steam/Steam/steamapps/common/'Conan Exiles Dedicated Server'/ConanSandboxServer.exe -log


        serviceAccount:
          # Specifies whether a service account should be created
          create: true
          # Automatically mount a ServiceAccount's API credentials?
          automount: true
          # Annotations to add to the service account
          annotations: {}
          # The name of the service account to use.
          # If not set and create is true, a name is generated using the fullname template
          name: ""

        podAnnotations: {}
        podLabels: {}

        podSecurityContext:
          # fsGroup: 1001

        securityContext:
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault

        service:
          type: LoadBalancer
          gameport: 7777

        storage:
          name: "conan-exiles-data"
          accessMode: ""
          storageClassName: "longhorn"
          capacity: "40Gi"
          annotations: {}

        resources:
          # We usually recommend not to specify default resources and to leave this as a conscious
          # choice for the user. This also increases chances charts run on environments with little
          # resources, such as Minikube. If you do want to specify resources, uncomment the following
          # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
          limits:
            cpu: 4000m
            memory: 10190Mi
          requests:
            cpu: 4000m
            memory: 8192Mi

        autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 100
          targetCPUUtilizationPercentage: 80
          # targetMemoryUtilizationPercentage: 80


        # Additional volumes on the output Deployment definition.
        volumes:
          - name: data
            persistentVolumeClaim:
              claimName: conan-exiles-data
          - name: run-cm
            configMap:
              name: runserver

        # Additional volumeMounts on the output Deployment definition.
        volumeMounts:
          - mountPath: /home/steam/Steam
            name: data
          - mountPath: /usr/local/bin/run_server.sh
            subPath: run_server.sh
            name: run-cm

        nodeSelector: {}

        tolerations: []

        affinity: {}

