cilium:
  kubeProxyReplacement: true
  ipam:
    mode: kubernetes
  podSecurityContext:
    # -- AppArmorProfile options for the `cilium-agent` and init containers
    appArmorProfile:
      type: "Unconfined"
  securityContext:
    capabilities:
      ciliumAgent:
        - CHOWN
        - KILL
        - NET_ADMIN
        - NET_RAW
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        - SETUID
        - SETGID
      cleanCiliumState:
        - NET_ADMIN
        - SYS_ADMIN
        - SYS_RESOURCE
  cgroup:
    hostRoot: /sys/fs/cgroup
    autoMount:
      enabled: false
  externalIPs:
    enabled: true
  l2announcements:
    enabled: true
  # Enable Cilium Ingress Controller
  ingressController:
    enabled: false
  # Use KubePrism to access cluster API
  k8sServiceHost: localhost
  k8sServicePort: 7445
  # Enable Hubble
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
      # service:
      #   annotations:
      #     # Enable Omni Workload Proxying for this service
      #     omni-kube-service-exposer.sidero.dev/port: "50080"
      #     omni-kube-service-exposer.sidero.dev/label: Hubble
