apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rei-nginx
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/malahayatii/homelab
      path: apps/projects/incubator/webservers/rei-nginx/deployment
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rei-nginx