apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: storage
type: Opaque
data:
  AWS_ACCESS_KEY_ID: WnJxTUNrMDEybU5NYTg0Qlp4dmc= # access-key
  AWS_SECRET_ACCESS_KEY: eEZUV0FRT201WTRJR3ZtYk5PSVd2bE9MUTY3RjNuM1BPVmVXcTlYaA== # secret-key
  AWS_ENDPOINTS: bG9uZ2hvcm4tYmFja3VwLmt1YmVsaXplLmNvbQ== # https://longhorn-backup.kubelize.com