apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
spec:
  source:
    helm:
      valueFiles:
        - $values/apps/operators/incubator/connectivity/teleport-kube-agent/values/dev-dhe/values.yaml