apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
     argocd.argoproj.io/sync-wave: "1"
  name: mck
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.230-192.168.1.240
  autoAssign: true