apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  annotations:
     argocd.argoproj.io/sync-wave: "1"
  name: default
  namespace: metallb-system
spec:
  addresses:
  - # insert ip-pool
  autoAssign: true