apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  source:
    repoURL: https://charts.longhorn.io
    targetRevision: 1.8.0
    chart: longhorn
    helm:
      parameters: []
      objectValues:
        longhorn:
          persistence:
            defaultClassReplicaCount: 2