apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-testpage-claim
  namespace: nginx-testpage
  annotations: 
    kubevirt.io/provisionOnNode: prod-svc-270224
spec:
  storageClassName: kubevirt-hostpath-provisioner
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi