apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-image-registry
spec:
  validationFailureAction: enforce
  background: false
  rules:
  - name: restrict-image-registry
    match:
      resources:
        kinds:
        - Pod
        namespaceSelector:
          matchLabels:
            security: enforced
    validate:
      message: "Only images from myregistry.com are allowed"
      pattern:
        spec:
          containers:
          - image: "myregistry.com/*"