apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        service:
          type: LoadBalancer
          annotations:
            service.beta.kubernetes.io/hetzner-load-balancer-type: "lb11"
            load-balancer.hetzner.cloud/network-zone: "eu-central"
            load-balancer.hetzner.cloud/location: "nbg1"
        ports:
          b01-prod:
            port: 2283
            protocol: TCP
            expose:
              default: true
            exposedPort: 2283
          b02-prod:
            port: 33333
            protocol: TCP
            expose:
              default: true
            exposedPort: 33333
          b02-test:
            port: 33334
            protocol: TCP
            expose:
              default: true
            exposedPort: 33334
          b01a-prod:
            port: 42069
            protocol: TCP
            expose:
              default: true
            exposedPort: 42069
        ingressRoute:
          dashboard:
            enabled: true