apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: observability-system
  name: http-metrics
  labels:
    app: http-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-metrics
  template:
    metadata:
      labels:
        app: http-metrics
    spec:
      containers:
       - name: http-metrics
         image: kubelize/http-metrics:0.0.3
         imagePullPolicy: Always
         ports:
          - containerPort: 80
            name: http
         volumeMounts:
          - mountPath: usr/share/nginx/html
            name: metrics
         resources:
           limits:
             cpu: 1000m
             memory: 1Gi
           requests:
             cpu: 1000m
             memory: 1Gi 
        #  securityContext:
        #    runAsNonRoot: true
        #    runAsUser: 1000
        #    allowPrivilegeEscalation: false
        #    capabilities:
        #      drop:
        #      - ALL
        #    seccompProfile: 
        #     type: RuntimeDefault
      volumes:
       - name: metrics
         persistentVolumeClaim:
           claimName: http-metrics