apiVersion: v1
kind: Service
metadata:
  name: http-metrics
  namespace: observability-system
spec:
  selector:
    app: http-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort