apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: http-metrics
  name: http-metrics
  namespace: observability-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: mayastor-3
  volumeMode: Filesystem
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi