apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # operators stable
  - ../../../apps/operators/stable/connectivity/cert-manager/
  - ../../../apps/operators/stable/connectivity/ingress-nginx/
  - ../../../apps/operators/stable/connectivity/teleport-kube-agent/

  # operators incubator
  - ../../../apps/operators/incubator/security/sealed-secrets-controller/
  - ../../../apps/operators/incubator/gitops/fluxcd/
  - ../../../apps/operators/incubator/gitops/tofu-controller/

  # addons
  - ../../../apps/addons/gitops/projects-bootstrap/home-mck/
  - ../../../apps/addons/cilium-config/address-pools/site-mck/
  - ../../../apps/addons/cilium-config/l2advertisements/
  - ../../../apps/addons/alertmanager-config/home-mck/
  - ../../../apps/addons/teleport-kube-agent/join-token/home-mck/


patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml
  - target:
      kind: Application
      name: ingress-nginx
    path: config/values/ingress-nginx/values.yaml