---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: teleport-kube-agent-join-token
  namespace: teleport-kube-agent
spec:
  encryptedData:
    auth-token: AgBtBK3rDHKW5Pt3Snmbw54EimdimzHK/otZ2zgi6vZ2a5FfqZRRo+zKw4uc+hcHScEJRDNDmO9S9ktxuAHoqjBHSQNTdh4sghOtKofyNXzjvRHpQstXdJnjCpdBjz55fAzvjCSvDV7zRugfsQ12YV6yEt52LDMZqqrHjtOMayybJg68dCYKi8sVaSzO9dIivY3Hp6StrPUB3Dio4IkFiNya8t/x7JwC+Ee0SJeQEln0v32zDnV91CrK599Y17BG07zIS6+UPe6MYYw7GH83b/O4z0hYegZqe/ZBIWzNjp05ZAyfZLFx2u70+BU9Uvxmy1S5Y3gIV+wv0MUq3yHzRDMhQiO1f5EKj/tduiffpatBcC1zOzfb6NEvxkXMfpN7hwNPEJ3WWHnNgwqI1Z1KXJCHCP21Tg67al11F6pWEKNOr+BQisUSEEIZrNGVx9i9dyVPHOjMaklpPqlpf7pHmcYFy7bRdIcdk5T9JEHBsSul735/25RN7NhALoaF8eOczE2hj15a3PegTg+oRSPGfc0zcE0iOY+FpeMH+tWKWq4k7XgJLj+5ZPg21/UZsBYIlm7n177968QRfnTG2mHyGGkHNdlcTas2p28wnobeQRS11bmdzYeMTr83VsKZESVirvFieSGcVITgqF2q+0zVkin6E39Yg9pQCS5hXvevsB/dHsF+UV9V+WXG4ObeJziAgpBEwqSHtZBELpB38MqWC0LVIThqFSTFVNPKTXVxKKvfqA==
  template:
    metadata:
      creationTimestamp: null
      name: teleport-kube-agent-join-token
      namespace: teleport-kube-agent
    type: Opaque
