apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: disallow-egress
  namespace: jellyfin
spec:
  podSelector:
    matchLabels:
      app: qbittorrent
  policyTypes:
    - Egress
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0