apiVersion: v1
data:
  password: cFhoZXJeSjJpUG1xNXhebyZoMzVYbnAzelVZWmlpMkRNakIhR141cVhBaDd6eUNDcnBFKmtFS1oqJipaVjZSWUA4Q1A5QEpIbiFWRnZ3ajg2R0hr
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak-test
type: Opaque