apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-test
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak-test
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 21.4.5
    chart: keycloak
    helm:
      parameters: []
      values: |
        auth:
          adminUser: identity-orchestrator
          existingSecret: keycloak-admin-credentials
          passwordSecretKey: password
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: false
        extraEnvVars:
        - name: KC_HEALTH_ENABLED
          value: "false"
        - name: KC_LOG_LEVEL
          value: info
        production: false
        replicaCount: 1
        pdb:
          create: false
          minAvailable: ""
          maxUnavailable: ""
        postgresql:
          enabled: true
          auth:
            postgresPassword: "test1"
            username: bn_keycloak
            password: "test2"
            database: bitnami_keycloak
            existingSecret: ""
          architecture: standalone