apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # operators stable
  - ../../../apps/operators/stable/observability/hcloud-prometheus-stack/
  - ../../../apps/operators/stable/connectivity/teleport-kube-agent/
  - ../../../apps/operators/stable/observability/uptime-kuma/
  - ../../../apps/operators/stable/connectivity/traefik/
  - ../../../apps/operators/stable/gitops/fluxcd/

  # addons
  - ../../../apps/addons/gitops/projects-bootstrap/kubelize-root/

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml
  - target:
      kind: Application
      name: uptime-kuma
    path: config/values/uptime-kuma/values.yaml