apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:

  - ../../../apps/operators/stable/connectivity/teleport-kube-agent/
  - ../../../apps/operators/stable/observability/uptime-kuma/

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml
  - target:
      kind: Application
      name: uptime-kuma
    path: config/values/uptime-kuma/values.yaml