apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        ingress:
          api:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
            host: longhorn-backup.kubelize.com
            path: /
            pathType: Prefix
            tls:
              - hosts:
                  - longhorn-backup.kubelize.com
                secretName: longhorn-backup-tls