# rickrlcraft deployment using docker image kubelize/minecraft-rlcraft
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlcraft
  labels:
    app: rlcraft
  namespace: minecraft
spec:
  template:
    metadata:
      name: rlcraft
      labels:
        app: rlcraft
    spec:
      initContainers:
        - name: init-unzip
          image: kubelize/rlcraft-unzip:0.1.0
          command: ["sh", "-c", "unzip -n /tmp/rlcraft_server.zip -d /home/mc/data"]
          volumeMounts:
          - name: rlcraft
            mountPath: /home/mc/data
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /home/mc/data"]
          volumeMounts:
          - name: rlcraft
            mountPath: /home/mc/data
      containers:
        - name: rlcraft
          image: kubelize/minecraft-rlcraft:0.1.2
          imagePullPolicy: Always
          command: ["/usr/local/bin/entrypoint.sh"]
          ports:
            - containerPort: 25565
              name: gameport
              protocol: TCP
            - containerPort: 25575
              protocol: TCP
              name: rconport
            - containerPort: 24454
              protocol: UDP
              name: voipport
          volumeMounts:
            - mountPath: /home/mc/data
              name: rlcraft
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: rlcraft
          persistentVolumeClaim:
            claimName: rlcraft
  replicas: 1
  selector:
    matchLabels:
      app: rlcraft
