# rickrlcraft deployment using docker image kubelize/minecraft-rlcraft
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rlcraft
  labels:
    app: rlcraft
  namespace: minecraft
spec:
  template:
    metadata:
      name: rlcraft-pod
      labels:
        app: rlcraft
    spec:
      containers:
        - name: rlcraft
          image: kubelize/minecraft-rlcraft:0.0.5
          ports:
            - containerPort: 25565
              name: gameport
            - containerPort: 25575
              name: rconport
          volumeMounts:
            - mountPath: /home/mc/rlcraft_server
              name: rlcraft
      volumes:
        - name: rlcraft
          persistentVolumeClaim:
            claimName: rlcraft
  replicas: 1
  selector:
    matchLabels:
      app: rlcraft
