# service
apiVersion: v1
kind: Service
metadata:
  name: rlcraft-rcon
  namespace: minecraft
spec:
  selector:
      app: rlcraft
  ports:
    - protocol: TCP
      name: rconport
      port: 25575
      targetPort: 25575
