# service
apiVersion: v1
kind: Service
metadata:
  name: rlcraft
  namespace: minecraft
spec:
  selector:
      app: rlcraft
  ports:
    - protocol: UDP
      name: gameport
      port: 25565
      targetPort: 25565
  type: LoadBalancer