# service
apiVersion: v1
kind: Service
metadata:
  name: rlcraft
  namespace: minecraft
spec:
  selector:
      app: rlcraft
  ports:
    - protocol: TCP
      name: gameport
      port: 25565
      targetPort: 25565
    - protocol: UDP
      name: voipport
      port: 24454
      targetPort: 24454
  type: LoadBalancer