# service
apiVersion: v1
kind: Service
metadata:
  name: rlcraft
  namespace: minecraft
spec:
  selector:
      app: rlcraft
  ports:
    - protocol: TCP
      name: gameport
      port: 25565
      targetPort: 25565
    - protocol: TCP
      name: rconport
      port: 25575
      targetPort: 25575