apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rlcraft
  namespace: rlcraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi