# service
apiVersion: v1
kind: Service
metadata:
  name: rlcraft-rcon
  namespace: minecraft
spec:
  selector:
      app: rlcraft
  ports:
    - protocol: UDP
      name: voipport
      port: 24454
      targetPort: 24454
