apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operators/stable/gitops/renovate/renovate-env.yaml
  - operators/incubator/connectivity/teleport-kube-agent/teleport-kube-agent-join-token.yaml
  - projects/incubator/gameservers/minecraft/minecraft-rcon-password.yaml
  - operators/incubator/security/keycloak/keycloak-admin-credentials.yaml
  - operators/incubator/security/keycloak/keycloak-database-credentials.yaml
  - operators/stable/observability/kube-prometheus-stack/alertmanager-config.yaml