apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operators/incubator/connectivity/teleport-agent/teleport-kube-agent-join-token.yaml
  # - operators/incubator/security/keycloak/keycloak-admin-credentials.yaml
  # - operators/incubator/security/keycloak/keycloak-database-credentials.yaml