apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-nginx
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: daniel.i.hendricken@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-nginx-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx