machine:
  kubelet:
    extraMounts:
      - destination: /var/mnt/storage
        type: bind
        source: /var/mnt/storage
        options:
          - bind
          - rshared
          - rw
 
  disks:
      - device: /dev/sdb # The name of the disk to use.
        partitions:
          - mountpoint: /var/mnt/storage # Where to mount the partition.