apiVersion: v1
kind: Secret
metadata:
  name: home-mck-metadata
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    environment: home
type: Opaque
data:
  server: aHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3Zj # "https://kubernetes.default.svc"
  name: aG9tZS1tY2s=  # "home-mck"
