apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # projects stable
  # - ../../../../apps/projects/stable/gameservers/palworld/
  # - ../../../../apps/projects/stable/gameservers/minecraft/
  
  # projects incubator
  # - ../../../../apps/projects/incubator/websevices/rei-nginx/
  # - ../../../../apps/projects/incubator/tools/arm-ripper/
  # - ../../../../apps/projects/incubator/websevices/nginx-testpage/
  # - ../../../../apps/projects/incubator/websevices/kubelize-nextra/
  # - ../../../../apps/projects/stable/gameservers/conan-exiles/
  # - ../../../../apps/projects/incubator/knowledgedbs/affine-pro/
  - ../../../../apps/projects/incubator/fileshare/nextcloud-prod/
  - ../../../../apps/projects/incubator/gameservers/web-rcon-prod-mck/
  # - ../../../../apps/projects/incubator/webservices/kubelize-nextra/
  - ../../../../apps/projects/incubator/wikis/wikijs/
  # - ../../../../apps/projects/incubator/gameservers/dawncraft/
  - ../../../../apps/projects/incubator/gameservers/atm9-itzg/

patches:
- target:
    kind: Application
    name: wikijs
  path: config/values/wikijs/values.yaml