apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/kubelize/kube-builder
      path: clusters/prod-mck/secrets
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd