apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.10.1
    chart: ingress-nginx
    helm:
      parameters: []
      values: |
        controller:
          allowSnippetAnnotations: true