apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.12.0
    chart: ingress-nginx
    helm:
      parameters: []
      valuesObject:
        controller:
          allowSnippetAnnotations: true
          config:
            annotations-risk-level: "Critical"