apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhe
  namespace: cilium-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dhe
  template:
    metadata:
      labels:
        app: dhe
    spec:
      nodeName: talos-430-o8e
      containers:
      - name: dhe-container
        image: wbitt/network-multitool:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mck
  namespace: cilium-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mck
  template:
    metadata:
      labels:
        app: mck
    spec:
      nodeName: talos-u3v-5z0
      containers:
      - name: mck-container
        image: wbitt/network-multitool:latest