apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject: 
        storage:
          name: "uptime-kuma"
          accessMode: ""
          storageClassName: "proxmox"
          capacity: "10Gi"
          annotations: {}