apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sdtdserver-data
  namespace: sdtd-server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi