apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: heya-immobilien-wp
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: heyya-immobilien-wp
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 23.1.4
    chart: wordpress
    helm:
      parameters: []
      values: |