# service
apiVersion: v1
kind: Service
metadata:
  name: dawncraft
  namespace: minecraft
spec:
  selector:
      app: dawncraft
  ports:
    - protocol: TCP
      name: gameport
      port: 25565
      targetPort: 25565
  type: LoadBalancer