apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawncraft
  namespace: minecraft
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi