apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox
parameters:
  csi.storage.k8s.io/fstype: ext4
  storage: zoom
  cache: writeback
  ssd: "true"
provisioner: csi.proxmox.sinextra.dev
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
