apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # projects stable
  
  # projects incubator
  - ../../../../apps/projects/incubator/fileshare/nextcloud-dev/
  - ../../../../apps/projects/incubator/gameservers/minecraft/
  - ../../../../apps/projects/incubator/gameservers/web-rcon-dev-dhe/
  - ../../../../apps/projects/incubator/wikis/wikijs/

patches:
  - target:
      kind: Application
      name: wikijs
    path: config/values/wikijs-test/values.yaml