apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        ingress:
          api:
            enabled: true
            ingressClassName: nginx
            host: longhorn-backup.mckensy.xyz
            path: /
            pathType: Prefix
            tls:
              - hosts:
                  - longhorn-backup.mckensy.xyz
                secretName: longhorn-backup-tls