apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # operators stable
  - ../../../apps/operators/stable/connectivity/cert-manager/
  - ../../../apps/operators/stable/connectivity/ingress-nginx/
  - ../../../apps/operators/stable/gitops/renovate/
  - ../../../apps/operators/stable/connectivity/teleport-kube-agent/

  # operators incubator
  - ../../../apps/operators/incubator/security/sealed-secrets-controller/
  - ../../../apps/operators/incubator/gitops/fluxcd/
  - ../../../apps/operators/incubator/gitops/tofu-controller/
  - ../../../apps/operators/incubator/storage/minio/

  # addons
  - ../../../apps/addons/gitops/projects-bootstrap/home-dhe/
  - ../../../apps/addons/cilium-config/address-pools/site-dhe/
  - ../../../apps/addons/cilium-config/l2advertisements/
  - ../../../apps/addons/alertmanager-config/home-dhe/
  - ../../../apps/addons/teleport-kube-agent/join-token/home-dhe/
  - ../../../apps/addons/storage/minio-tenants/etcd-backup/
  - ../../../apps/addons/storage/minio-tenants/etcd-backup/home-dhe/
  - ../../../apps/addons/storage/minio-tenants/longhorn-backup/
  - ../../../apps/addons/storage/minio-tenants/longhorn-backup/home-dhe/

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml
  - target:
      kind: Application
      name: ingress-nginx
    path: config/values/ingress-nginx/values.yaml
  - target:
      kind: Application
      name: longhorn-backup
    path: config/values/longhorn-backup/values.yaml