apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # operators
  - ../../../apps/operators/stable/connectivity/cert-manager/
  - ../../../apps/operators/stable/connectivity/ingress-nginx/
  - ../../../apps/operators/stable/gitops/renovate/
  - ../../../apps/operators/stable/connectivity/teleport-kube-agent/
  - ../../../apps/operators/stable/gitops/fluxcd/
  - ../../../apps/operators/stable/gitops/tofu-controller/

  # addons
  - ../../../apps/addons/gitops/projects-bootstrap/home-dhe/
  - ../../../apps/addons/cilium-config/address-pools/site-dhe/
  - ../../../apps/addons/cilium-config/l2advertisements/
  - ../../../apps/addons/storage/csi-proxmox/pve-dhe/
  - ../../../apps/addons/issuers/

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml
  - target:
      kind: Application
      name: ingress-nginx
    path: config/values/ingress-nginx/values.yaml
  - target:
      kind: Application
      name: uptime-kuma
    path: config/values/uptime-kuma/values.yaml