apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # operators stable
  - ../../../apps/operators/stable/connectivity/cert-manager/
  - ../../../apps/operators/stable/connectivity/ingress-nginx/
  - ../../../apps/operators/stable/gitops/renovate/
  - ../../../apps/operators/stable/connectivity/metallb/
  - ../../../apps/operators/stable/connectivity/teleport-kube-agent/

  # operators incubator
  - ../../../apps/operators/incubator/security/sealed-secrets-controller/
  - ../../../apps/operators/incubator/gitops/fluxcd/
  - ../../../apps/operators/incubator/gitops/tofu-controller/

  # addons
  - ../../../apps/addons/metallb-config/address-pools/site-dhe
  - ../../../apps/addons/metallb-config/l2advertisement
  - ../../../apps/addons/alertmanager-config/alertmanager-home-dhe.yaml

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml
