apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-cluster
  source:
    repoURL: https://charts.releases.teleport.dev
    targetRevision: 16.0.1
    chart: teleport-cluster
    helm:
      parameters: []
      values: |
        clusterName: teleport.kubelize.com
        proxyListenerMode: multiplex
        acme: true
        acmeEmail: kubelize@kubelize.com