apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.15.4
    chart: sealed-secrets
    helm:
      parameters: []
      values: |
        # Make sure Ingress is disabled for security reasons
        ingress:
          enabled: false
