apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
spec:
  sources:
    - repoURL: https://github.com/kubelize/kube-builder
      targetRevision: dev
      path: apps/operators/stable/connectivity/teleport-kube-agent/deploy
    - repoURL: https://charts.releases.teleport.dev
      targetRevision: 16.4.10
      chart: teleport-kube-agent
      helm:
        valuesObject:
          kubeClusterName: prod-mck
          proxyAddr: teleport.kubelize.com:443
          apps:
          - name: home-mck-etcd-backup
            uri: https://etcd-backup-console.minio-system.svc.cluster.local:9443
            insecure_skip_verify: true
          - name: home-mck-pihole
            uri: http://pihole-web.pihole.svc.cluster.local:80/admin
          - name: mck-pve
            uri: https://192.168.1.211:8006
            insecure_skip_verify: true
          - name: home-mck-grafana
            uri: http://monitoring-kube-prometheus-stack-grafana.monitoring.svc.cluster.local
          - name: home-mck-prometheus
            uri: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          - name: home-mck-alertmanager
            uri: http://alertmanager-operated.monitoring.svc.cluster.local:9093
          - name: home-mck-uptime-kuma
            uri: http://uptime-kuma.monitoring.svc.cluster.local:3001
          - name: home-mck-argocd
            uri: http://argocd-server.argocd.svc.cluster.local
          - name: home-mck-longhorn
            uri: http://longhorn-frontend.storage.svc.cluster.local
          - name: home-mck-hubble
            uri: http://hubble-ui.kube-system.svc.cluster.local
          - name: home-mck-web-rcon
            uri: https://web-rcon-service.web-rcon.svc.cluster.local
            insecure_skip_verify: true
            rewrite:
              headers:
                - "Connection: Upgrade"
                - "Upgrade: websocket"
                - "Host: home-mck-web-rcon.teleport.kubelize.com"
                - "Scheme: wss"
                - "Filename: /ws"
          roles: "kube,app,discovery"
          kubernetesDiscovery:
          - types: ["app"]
            namespaces: ["*"]
            labels:
              "teleport.dev/enabled": "true"
          - types: ["app"]
            namespaces: ["*"]
            labels:
              "teleport.dev/enabled": "on"
          joinTokenSecret:
            create: false
          podSecurityPolicy:
            enabled: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 265Mi
          initSecurityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 9807
            seccompProfile:
              type: RuntimeDefault
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 9807
            seccompProfile:
              type: RuntimeDefault
