apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        kubeClusterName: home-mck
        highAvailability:
          replicaCount: 2
          requireAntiAffinity: true
        apps:
          # - name: home-mck-longhorn-backup
          #   uri: https://longhorn-backup-console.longhorn-backup.svc.cluster.local:9443
          #   insecure_skip_verify: true
          # - name: home-mck-etcd-backup
          #   uri: https://etcd-backup-console.etcd-backup.svc.cluster.local:9443
          #   insecure_skip_verify: true
          - name: mck-pve
            uri: https://192.168.1.211:8006
            insecure_skip_verify: true
          - name: home-mck-grafana
            uri: http://monitoring-kube-prometheus-stack-grafana.monitoring.svc.cluster.local
          - name: home-mck-prometheus
            uri: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
          - name: home-mck-alertmanager
            uri: http://alertmanager-operated.monitoring.svc.cluster.local:9093
          - name: home-mck-argocd
            uri: http://argocd-server.argocd.svc.cluster.local
          - name: home-mck-hubble
            uri: http://hubble-ui.kube-system.svc.cluster.local
          - name: home-mck-web-rcon
            uri: https://web-rcon-service.web-rcon.svc.cluster.local
            insecure_skip_verify: true
            rewrite:
              headers:
                - "Connection: Upgrade"
                - "Upgrade: websocket"
                - "Host: home-mck-web-rcon.teleport.kubelize.com"
                - "Scheme: wss"
                - "Filename: /ws"