apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment/deployment.yaml
  - deployment/service.yaml
  - deployment/configmap.yaml
  - deployment/pv.yaml
  - deployment/pvc.yaml