apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # operators stable
  - ../../../apps/operators/stable/connectivity/cert-manager/
  - ../../../apps/operators/stable/connectivity/ingress-nginx/

  # operators incubator
  - ../../../apps/operators/incubator/security/sealed-secrets-controller/
  - ../../../apps/operators/incubator/connectivity/teleport-kube-agent/
  - ../../../apps/operators/incubator/observability/uptime-kuma/

patches:
  - target:
      kind: Application
      name: teleport-kube-agent
    path: config/values/teleport-kube-agent/values.yaml