apiVersion: v1
kind: Service
metadata:
  name: test2-service
  namespace: minecraft
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  selector:
    run: test2