apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-kube-agent
  sources:
    - repoURL: https://github.com/kubelize/kube-builder
      targetRevision: dev
      path: apps/operators/stable/connectivity/teleport-kube-agent/deploy
    - repoURL: https://charts.releases.teleport.dev
      targetRevision: 16.2.0
      chart: teleport-kube-agent