apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-addons
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/malahayatii/homelab
      path: apps/addons/metallb-config
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd