---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-prometheus-kube-prometheus-alertmanager
  namespace: monitoring
spec:
  encryptedData:
    alertmanager.yml: AgCZqZ7ENNoRc+omy8YUH23LfxMd80IMWDkvwbmria0nI1raQRfnWcvEW40mXLG97HvUFO6mdC+9MRKBW6pVMEPq8n9ZnL+KqYF1JztDfbsgISYH4J9xChPSOj0nwqWgjL17Q+HKKfpl34SakQiBxy5xs6ifmY2sqgimXWt0Zy1C6TacMb7MYoK0SHvXPgIorFEwLRd03C/OFC9sJbfEbh61gTcAbMdU27fMkeEeoFL2iTFsVooWlvfJv0u2WsZGpapOIVnnR0ZrjQH4/bp2NOm0Say1LCcMZa/apVOlMnGYYBZ/2POCxOcJgTPCn6+EBpOjx7DGdza4HHnN1WAvT9EgSAU/Bz32xw5FGlPeih04eZXHzOQ2Q17tgMiPbSUNKTvqUFVZt79JwGf16y3Bvtaos/d+FuYHMLSPwy74P4nQJ6uZa7eRd06oHyIzWhnxVPnOPBKIbP/r1AHSORaNI6mO0RgOw9InwtIr2sV0OLFkiUx/K2Sm/DFq1pyaWyq6mipBZtBmDF5HIqrCJsweWx7YASeJhR8z8JUU6U9Ivu42kELFDbSp48gC0U+nAYgf7WVPafIOuxBKH8NwMD2AYnLwNjPyRimhzeVkQmEywcmxQ3598YndnWQ+fFRfXqlnfc9JRQ+CBmsvWfP+qtLnppXZ7qLLfgBlh9tao/NDyq610YSjxEowGLjBpFD3eIcftF6Y+9it/fw7n1PT4P2OJv80pW63o4opYR+hOXHcyaODZm8kfDLHzwPeHLjWcbyQijyQHfT8e+7Wgf34/iSEg2j8MiY9U/qLKDD9ksCjAkBNN4WomgA5JyBbS00zm6IL0ndnwzUTrQYk66r5xWLcW0jgKmCGmH6dKB5BlSj0w7SHtVW33/OksB5088HC8ZHHsOJnyq4LTPEAZUXWs5bBTZiLlgWA3T0IfP+A7zVWEIGm0KJj8K9EE6xTp7J5njijrDqJe7FGjSPyolT29lQAhv52gwHhP9ViNInZf2pz/a8E0sDg3/urJUji7yhw9Eq96zeSd2gpJV62jPQj31T68oOXz6ydyL9bavbwg/afO5aWT9113iCmoCcoohVXrg3QPzSpv9bZMVS0ZaxHFWx2yANc9CyEtUbFlOQwSOvJtAl3f2W/vdkEOXE/B0+VZy4usxi+FxfXNK2EzJseC5QN8kSXlMMv/MuwAM431plmAnaLbH2JPrqTP0ej8KpiYhDd/1rKv9eHd1x8OOTUl8odYkbmBORXbMRKzt/Qh4GMhqpV2zVEVtqVD+Of2KLO0Hxao1rxbZe+Og8CMFkEpUBdpBwkP9LgKipSR5ZShG0mRAj74PnYPle4O2liSGp7GUMybfF09olZVe4Fbp9LFyZ6/035IBl84oGGtjGZze4HHWFSmJT1CPSiwb6hgVWhdIJmw03RAoB7oP7WGCkGQwhcjEO5c++rKFXVcdOHAJZmHiYMOmJ8+fwe5xTBhxbligNq
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-prometheus-kube-prometheus-alertmanager
      namespace: monitoring
    type: Opaque
