kube-prometheus-stack:
  # NOTE: These must be set manually to the control plane IP addresses
  #kubeEtcd:
  #  endpoints:
  #    - x.y.z.a
  #    - x.y.z.b
  #    - x.y.z.c
  kubeControllerManager:
    service:
      selector:
        k8s-app: kube-controller-manager
  kubeScheduler:
    service:
      selector:
        k8s-app: kube-scheduler
  alertmanager:
    alertmanagerSpec:
      forceEnableClusterMode: true
      # useExistingSecret: true
      # secrets:
      #   - alertmanager-config
      storage:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
  prometheus:
    prometheusSpec:
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 150Gi
  grafana:
    grafana.ini:
      auth:
        # testing auth configurations currently
        disable_login_form: false
        disable_signout_menu: false
      auth.basic:
        enabled: true
      auth.anonymous:
        enabled: true
    # Allow Omni Workload Proxying for this service
      security:
        allow_embedding: true
    service:
      annotations:
        omni-kube-service-exposer.sidero.dev/port: "50082"
        omni-kube-service-exposer.sidero.dev/label: Grafana
