apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-kube-agent
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-kube-agent
  source:
    repoURL: https://charts.releases.teleport.dev
    targetRevision: 16.1.0
    chart: teleport-kube-agent
    helm:
      valuesObject: {}