apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        ingress:
          api:
            enabled: true
            ingressClassName: nginx
            host: etcd-backup.kubelize.com
            path: /
            pathType: Prefix
            tls:
              - hosts:
                  - etcd-backup.kubelize.com
                secretName: etcd-backup-tls