apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: patch
spec:
  source:
    helm:
      valuesObject:
        kubeClusterName: kubelize-root
        apps:
          - name: kubelize-root-argocd
            uri: http://argocd-server.argocd.svc.cluster.local
          - name: kubelize-root-grafana
            uri: http://kube-prometheus-stack-grafana.observability-system.svc.cluster.local
          - name: kubelize-root-prometheus
            uri: http://kube-prometheus-stack-prometheus.observability-system.svc.cluster.local:9090
          - name: kubelize-root-alertmanager
            uri: http://alertmanager-operated.observability-system.svc.cluster.local:9093
          - name: uptime-kuma
            uri: http://uptime-kuma.uptime-kuma.svc.cluster.local:3001
          - name: traefik
            uri: http://traefik-dashboard.traefik.svc.cluster.local:8080/dashboard/
            rewrite:
              redirect:
              - traefik.teleport.kubelize.com/dashboard
