apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno-system
  source:
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.4.1
    chart: kyverno
    helm:
      parameters: []
